version: '3.8'

services:
  telegram_bot:
    build:
      context: ./services/TelegramBot
      dockerfile: Dockerfile
    ports:
      - "8000:5000"
    volumes:
      - ./services/TelegramBot/app:/app/app

  redis:
    image: "redis:alpine"

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
